class Messages(object):
    RUN_ALGORTIHM = 'RUN_ALGORTIHM'
    PIPELINE_CREATED = 'PIPELINE_CREATED'
    PIPELINE_FINISHED = 'PIPELINE_FINISHED'
    ALGORITHM_REGISTER = 'ALGORITHM_REGISTER'
    ALGORTIHM_FINISHED_SUCCESS = 'ALGORTIHM_FINISHED_SUCCESS'
    ALGORTIHM_FINISHED_FAILED = 'ALGORTIHM_FINISHED_FAILED'
    PIPELINE_CREATE = 'PIPELINE_CREATE'
    PIPELINE_EXECUTE = 'PIPELINE_EXECUTE'


class Fields(object):
    flowInput = 'flowInput'
    pipeline = 'pipeline'


messages = Messages()
fields = Fields()

__all__ = ['fields', 'messages']
